[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "mud"
version = "0.1.0"
description = "A text adventure about confronting an impossible situation."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pygbag>=0.9.3",
    "pytest>=9.0.3",
    "ty>=0.0.33",
]

[tool.uv]
default-groups = ["dev"]
package = true
upgrade-package = ["ruff"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mud = [
    "assets/audio/*.ogg",
    "assets/fonts/*.ttf",
    "assets/images/*.png",
    "assets/text/**/*.txt",
]

[tool.ruff]
exclude = [
    "*.ipynb"
]
line-length = 88
indent-width = 4
target-version = "py312"
src = ["src"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "D",
    "UP",
    "TID",
    "BLE",
    "PLC",
    "SIM",
    "ANN",
]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.per-file-ignores]
"**/{test,docs}/*" = ["D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
