name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  format-lint-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv and Python
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install just
        uses: extractions/setup-crate@4993624604c307fbca528d28a3c8b60fa5ecc859 # v1.4.0
        with:
          repo: casey/just
          version: 1.42.4

      - name: Format and lint
        run: just format

      - name: Type check
        run: just check

  build-game:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv and Python
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install just
        uses: extractions/setup-crate@4993624604c307fbca528d28a3c8b60fa5ecc859 # v1.4.0
        with:
          repo: casey/just
          version: 1.42.4

      - run: just build

  ci-success:
    needs: [format-lint-check, build-game]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: CI Success
        run: echo "All CI checks passed!"
